name: Release workflow

on:
  workflow_call:
  workflow_dispatch:

jobs:
  staging:
    uses: ./.github/workflows/reusable.test.yml
    with:
      test-input-1: 1
      test-input-2: true
    secrets:
      test-secret-1: 'staging-secret-1'
      test-secret-2: 'staging-secret-2'
  production:
    needs: staging
    uses: ./.github/workflows/reusable.test.yml
    with:
      test-input-1: 2
      test-input-2: false
    secrets:
      test-secret-1: 'production-secret-1'
      test-secret-2: 'production-secret-2'
  eu-production:
    needs: staging
    uses: ./.github/workflows/reusable.test.yml
    with:
      test-input-1: 3
      test-input-2: true
    secrets:
      test-secret-1: 'eu-production-secret-1'
      test-secret-2: 'eu-production-secret-2'
