name: Release workflow

on:
  workflow_call:
  workflow_dispatch:

jobs:
  staging-1:
    uses: ./.github/workflows/reusable.test.yml
    with:
      test-input-1: 1
      test-input-2: true
    secrets:
      test-secret-1: 'staging-secret-1'
      test-secret-2: 'staging-secret-2'
  production-1:
    needs: staging-1
    uses: ./.github/workflows/reusable.test.yml
    with:
      test-input-1: 2
      test-input-2: false
    secrets:
      test-secret-1: 'production-secret-1'
      test-secret-2: 'production-secret-2'
  eu-production-1:
    needs: staging-1
    uses: ./.github/workflows/reusable.test.yml
    with:
      test-input-1: 3
      test-input-2: true
    secrets:
      test-secret-1: 'eu-production-secret-1'
      test-secret-2: 'eu-production-secret-2'
  staging-2:
    needs: staging-1
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
  production-2:
    needs: production-1
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
  eu-production-2:
    needs: eu-production-1
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
