name: Release workflow

on:
  workflow_call:
  workflow_dispatch:

jobs:
  staging:
    uses: nr-kkenney/testing-1234/.github/workflows/staging.yml@main
  production:
    needs: staging
    uses: nr-kkenney/testing-1234/.github/workflows/production.yml@main
  eu-production:
    needs: staging
    uses: nr-kkenney/testing-1234/.github/workflows/eu-production.yml@main
  test1:
    needs: staging
    uses: nr-kkenney/testing-1234/.github/workflows/reusable/test1.yml@main
  test2:
    needs: staging
    uses: nr-kkenney/testing-1234/.github/workflows/reusable/test2.yml@main
