name: Test

on:
  workflow_call:
    inputs:
      test-input-1:
        required: true
        type: number
      test-input-2:
        required: true
        type: boolean
        default: true
    secrets:
      test-secret-1:
        required: true
      test-secret-2:
        required: true

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: input-1
        run: |
          echo "${{ inputs.test-input-1 }}"

      - name: input-2
        run: |
          echo "${{ inputs.test-input-2 }}"

      - name: secret-1
        run: |
          echo "${{ secrets.test-secret-1 }}"

      - name: secret-2
        run: |
          echo "${{ secrets.test-secret-2 }}"

      - name: latest
        run: |
          echo ${GITHUB_REPOSITORY}

